#!/bin/bash

# The disc you will install must have four partitions.
# The first partition must be "efi", the second partition must be "linux-extended-boot"
# the third partition must be "root" and the fourth partition must be "home".

# cputype --> intel , amd
# kernel  --> linux , linux-lts , linux-zen , linux-hardened , linux-g14

#--------------------You can change-------------------------
targetdisk="/dev/nvme0n1"
# Config Options
cputype=""
kernel=""
# Username and Computer name
hostname=""
username=""
# User passwords
userpasswrd=""
rootpasswrd=""
# Language, vconsole font and timezone
locale="tr_TR.UTF-8"
keymap="trq"
font="LatArCyrHeb-16"
timezone="Europe/Istanbul"
#-----------------------------------------------------------

# Installation disk
targetefi=""$targetdisk"p1"
targetboot=""$targetdisk"p2"
targetroot=""$targetdisk"p3"
targethome=""$targetdisk"p4"
# Mount partitions
efimnt="/mnt/efi"
bootmnt="/mnt/boot"
rootmnt="/mnt"
homemnt="/mnt/home"

# Pacstrap
pacstrappacks=(
  base
  base-devel
  $kernel
  $kernel-headers
  linux-firmware
  $cputype-ucode
  util-linux
  coreutils
  e2fsprogs
  dosfstools
  neovim
  git
  networkmanager
)

# Packs
guipacs=(
  sbctl
  openssh
  procps-ng
  eza
  pacman-contrib
  bash-completion
  usbutils
  dialog
  xdg-user-dirs
  xdg-utils
  zip
  unzip
  unrar
  p7zip
  lzop
  tar
  samba
  nfs-utils
  bind
  bluez
  bluez-utils
  man-db
  man-pages
  acpi
  acpi_call-dkms
  efibootmgr
  edk2-shell
)

# Functions
bootloaderopts() {
  # Shell
  cp "$rootmnt"/usr/share/edk2-shell/x64/Shell.efi "$rootmnt"/efi/shellx64.efi
  # Systemd boot install
  arch-chroot "$rootmnt" bootctl --esp-path=/efi --boot-path=/boot --efi-boot-option-description="Arch Linux" install
  # Loader config
  printf "%s\n" "timeout  menu-force" "console-mode  max" | tee "$rootmnt"/efi/loader/loader.conf
  # Adds a pacman hook which is executed every time systemd is upgraded.
  mkdir -p "$rootmnt"/etc/pacman.d/hooks/
  printf "%s\n" "[Trigger]" "Type = Package" "Operation = Upgrade" "Target = systemd" "" "[Action]" "Description = Gracefully upgrading systemd-boot..." "When = PostTransaction" "Exec = /usr/bin/systemctl restart systemd-boot-update.service" | tee "$rootmnt"/etc/pacman.d/hooks/95-systemd-boot.hook
}

pacmanopts() {
  sed -i '/#Color/s/^#//g' "$rootmnt"/etc/pacman.conf
  sed -i '/#VerbosePkgLists/s/^#//g' "$rootmnt"/etc/pacman.conf
  sed -i 's/#ParallelDownloads = 5/ParallelDownloads = 3/g' "$rootmnt"/etc/pacman.conf
  # Acivate multilib repository
  sed -i "/\[multilib\]/,/Include/"'s/^#//' "$rootmnt"/etc/pacman.conf
}

sshopts() {
  #PermitRootLogin prohibit-password
  sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/g' "$rootmnt"/etc/ssh/sshd_config
  #PasswordAuthentication yes
  sed -i '/#PasswordAuthentication yes/s/^#//g' "$rootmnt"/etc/ssh/sshd_config
}

g14repo() {
  # Adding asus-linux repository
  pacman-key --recv-keys 8F654886F17D497FEFE3DB448B15A6B0E9A3FA35
  sleep 3
  pacman-key --finger 8F654886F17D497FEFE3DB448B15A6B0E9A3FA35
  sleep 3
  pacman-key --lsign-key 8F654886F17D497FEFE3DB448B15A6B0E9A3FA35
  sleep 3
  pacman-key --finger 8F654886F17D497FEFE3DB448B15A6B0E9A3FA35
  sleep 3

  printf "%s\n" "[g14]" "Server=https://naru.jhyub.dev/$repo" "#Server = https://arch.asus-linux.org" >>/etc/pacman.conf
  pacman -Sy
}
