#!/bin/bash

# Config Options
cputype="amd"
# Installation disk
targetdisk="/dev/nvme0n1"
targetefi="/dev/nvme0n1p1"
targetboot="/dev/nvme0n1p2"
targetroot="/dev/nvme0n1p3"
targethome="/dev/nvme0n1p4"
# Mount partitions
efimnt="/mnt/efi"
bootmnt="/mnt/boot"
rootmnt="/mnt"
homemnt="/mnt/home"
# Language, vconsole font and timezone
locale="tr_TR.UTF-8"
keymap="trq"
font="LatArCyrHeb-1"
timezone="Europe/Istanbul"
# Username and Computer name
hostname="PANTHERA-DR-ARCH"
username="drpars"

# Root part uuid
rootuuid=$(lsblk -dno PARTUUID "$targetroot")
swapuuid=$(findmnt -no UUID -T "$rootmnt"/swapfile)
swapopt=$(filefrag -v "$rootmnt"/swapfile | awk '$1=="0:" {print substr($4, 1, length($4)-2)}')

# Pacstrap
pacstrappacks=(
  base
  base-devel
  linux
  linux-firmware
  $cputype-ucode
  util-linux
  coreutils
  e2fsprogs
  dosfstools
  neovim
  git
  networkmanager
)

# Packs
guipacs=(
  sbctl
  procps-ng
  exa
  pacman-contrib
  bash-completion
  usbutils
  dialog
  xdg-user-dirs
  xdg-utils
  zip
  unzip
  unrar
  p7zip
  lzop
  tar
  samba
  nfs-utils
  bind
  bluez
  bluez-utils
  man-db
  man-pages
  acpi
  acpi_call-dkms
  efibootmgr
  edk2-shell
)

# Functions
bootloaderopts() {
  # Shell
  cp /usr/share/edk2-shell/x64/Shell.efi /efi/shellx64.efi
  # Systemd boot install
  bootctl --esp-path=/efi --boot-path=/boot --efi-boot-option-description="Arch Linux" install
  # Loader config
  printf "%s\n" "default  arch.conf" "timeout  menu-force" "console-mode 0" | tee /efi/loader/loader.conf
  # Loader entries config
  mkdir -p /efi/loader/entries
  printf "%s\n" "title   Arch Linux" "linux   /vmlinuz-linux" "initrd  /$cputype-ucode.img" "initrd  /initramfs-linux.img" "options root=PARTUUID=$rootuuid rw rootfstype=ext4 systemd.unit=graphical.target nvidia-drm.modeset=1 resume=UUID=$swapuuid resume_offset=$swapopt" | tee /boot/loader/entries/arch.conf
  # Adds a pacman hook which is executed every time systemd is upgraded.
  printf "%s\n" "[Trigger]" "Type = Package" "Operation = Upgrade" "Target = systemd" "" "[Action]" "Description = Gracefully upgrading systemd-boot..." "When = PostTransaction" "Exec = /usr/bin/systemctl restart systemd-boot-update.service" | tee /etc/pacman.d/hooks/95-systemd-boot.hook
}

pacmanopts() {
  sed -i '/#Color/s/^#//g' "$rootmnt"/etc/pacman.conf
  sed -i '/#VerbosePkgLists/s/^#//g' "$rootmnt"/etc/pacman.conf
  sed -i 's/#ParallelDownloads = 5/ParallelDownloads = 3/g' "$rootmnt"/etc/pacman.conf
  # Acivate multilib repository
  sed -i "/\[multilib\]/,/Include/"'s/^#//' "$rootmnt"/etc/pacman.conf
}

sshopts() {
  #PermitRootLogin prohibit-password
  sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/g' "$rootmnt"/etc/ssh/sshd_config
  #PasswordAuthentication yes
  sed -i '/#PasswordAuthentication yes/s/^#//g' "$rootmnt"/etc/ssh/sshd_config
}
