#!/bin/bash

# cputype --> intel , amd 
# kernel  --> linux , linux-lts , linux-zen , linux-hardened 

# Config Options
cputype=""
kernel=""
# Username and Computer name
hostname=""
username=""
# User passwords
userpasswrd=""
rootpasswrd=""
# Installation disk
targetdisk="/dev/nvme0n1"
targetefi="/dev/nvme0n1p1"
targetboot="/dev/nvme0n1p2"
targetroot="/dev/nvme0n1p3"
targethome="/dev/nvme0n1p4"
# Mount partitions
efimnt="/mnt/efi"
bootmnt="/mnt/boot"
rootmnt="/mnt"
homemnt="/mnt/home"
# Language, vconsole font and timezone
locale="tr_TR.UTF-8"
keymap="trq"
font="LatArCyrHeb-16"
timezone="Europe/Istanbul"

# Pacstrap
pacstrappacks=(
  base
  base-devel
  $kernel
  $kernel-headers
  $kernel-firmware
  $cputype-ucode
  util-linux
  coreutils
  e2fsprogs
  dosfstools
  neovim
  git
  networkmanager
)

# Packs
guipacs=(
  sbctl
  openssh
  procps-ng
  eza
  pacman-contrib
  bash-completion
  usbutils
  dialog
  xdg-user-dirs
  xdg-utils
  zip
  unzip
  unrar
  p7zip
  lzop
  tar
  samba
  nfs-utils
  bind
  bluez
  bluez-utils
  man-db
  man-pages
  acpi
  acpi_call-dkms
  efibootmgr
  edk2-shell
)

# Functions
bootloaderopts() {
  # Shell
  cp "$rootmnt"/usr/share/edk2-shell/x64/Shell.efi "$rootmnt"/efi/shellx64.efi
  # Systemd boot install
  arch-chroot "$rootmnt" bootctl --esp-path=/efi --boot-path=/boot --efi-boot-option-description="Arch Linux" install
  # Loader config
  printf "%s\n" "timeout  menu-force" "console-mode  max" | tee "$rootmnt"/efi/loader/loader.conf
  # Adds a pacman hook which is executed every time systemd is upgraded.
  mkdir -p "$rootmnt"/etc/pacman.d/hooks/
  printf "%s\n" "[Trigger]" "Type = Package" "Operation = Upgrade" "Target = systemd" "" "[Action]" "Description = Gracefully upgrading systemd-boot..." "When = PostTransaction" "Exec = /usr/bin/systemctl restart systemd-boot-update.service" | tee "$rootmnt"/etc/pacman.d/hooks/95-systemd-boot.hook
}

pacmanopts() {
  sed -i '/#Color/s/^#//g' "$rootmnt"/etc/pacman.conf
  sed -i '/#VerbosePkgLists/s/^#//g' "$rootmnt"/etc/pacman.conf
  sed -i 's/#ParallelDownloads = 5/ParallelDownloads = 3/g' "$rootmnt"/etc/pacman.conf
  # Acivate multilib repository
  sed -i "/\[multilib\]/,/Include/"'s/^#//' "$rootmnt"/etc/pacman.conf
}

sshopts() {
  #PermitRootLogin prohibit-password
  sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/g' "$rootmnt"/etc/ssh/sshd_config
  #PasswordAuthentication yes
  sed -i '/#PasswordAuthentication yes/s/^#//g' "$rootmnt"/etc/ssh/sshd_config
}
